### ISSUE TITLE
Article base doesn't working

### ISSUE THREAD

**Issue by devkbsc** [bradtraversy/articlebase#1]
Hello I am very begginer in Sails, I have just followed our tutorial and just try to create what exactly you did except the change of DBMS. I use Sails-Mysql in my case. 

I have created my API articles, and connected to the database. 

But It seems like i have some problem in retriving the object articles in EJS file. I can't execute any view file! Here it:

```
<h1>Articles</h1>
<table classs="table table-stripped">

    <thead>
        <tr>
            <th>#</th>
            <th>title</th>
            <th></th>
        </tr>
    </thead>
<tbody>
<% articles.forEach(function(article){ %>
    <tr>
         <td><% article.id %></td>
         <td><% article.title %></td>
    </tr>
<% }) %>
</tbody>
</table>
```

> Error meesage 
> {
>   "code": "E_INVALID_CRITERIA",
>   "details": "Could not use the provided `where` clause.  Could not filter by `id`: Does not match the declared data type of the corresponding attribute.  1 error validating value: \n • Specified value (a string: 'list') doesn't match the expected type: 'number'",
>   "message": "The server could not fulfill this request (`GET /articles/list`) due to a problem with the parameters that were sent.  See the `details` for more info.  **The following additional tip will not be shown in production**:  Tip: Check your client-side code to make sure that the request data it sends matches the expectations of the corresponding attribues in your model.  Also check that your client-side code sends data for every required attribute."
> }

**Comment by devkbsc** [comment]
I have changed in config/blueprints.js as follow 

actions : true. 

The problem fixed

**Comment by shubhamseth-work** [comment]
I have changed in config/blueprints.js as follow

actions : true.
and also you have change the shortcut attribute Boolean value of attribute 
shortcut : true
The problem fixed

**Comment by PratibhaBasapure** [comment]
Thank you..saved me today
